### ISSUE TITLE
Pseudo Issue to discuss some things in advance and independently!

### ISSUE THREAD

**Issue by antis81** [antis81/qTox#1]
Zetok, this is a local screenshot made with the unnamed project (you'll get to know it :smile:) of my forked qTox repo and your repo with all open PR's (your branches).

![bildschirmfoto von 2015-08-05 00 16 39](https://cloud.githubusercontent.com/assets/440517/9074183/a8df7b32-3b07-11e5-8ef7-bbd9cac12aac.png)

In theory I could merge (sign-off) those and push to my fork on Github. Of course I also don't have write access to the "original" repo -> we need an organisation to manage this here. If not possible to use the qtoxcore org (how is it called?), I suggest to create another one, called `qtox` (or maybe tox-clients). This can all be changed later. It's just to get things rolling ...

**Comment by zetok** [comment]
there's already `qTox` org - too bad that only @tux3 is the only member, and there are no repos there… https://github.com/qTox

Dunno whether org needs to be created or whether an already existing one could be used.
Creating new one certainly would feel like fresh (re-)start.

`Toxclients` wouldn't be the best name ever, but since there doesn't seem to be any better..
(Someone suggested `tox-clients`)

As for merging - some stuff from https://github.com/tux3/qTox/pulls should be merged

**Comment by antis81** [comment]
>Dunno whether org needs to be created or whether an already existing one could be used.
Creating new one certainly would feel like fresh (re-)start.

An organisation cannot be simply taken over by someone. It is "owned" by at least one person (tux3 in this case). Usually several people have full access to the orga, which is how it should be. So, things can always keep moving if someone isn't available.

**Comment by antis81** [comment]
@zetok Good News! Got Lifesign and pretty positive reply from tux3 ... :)

Here's what he wrote:

>Hi,
>
>I'm currently away on a trip, so I'm not actively  working on Tox, but I'm sure the project will appreciate all the help it  can get. Thanks for reaching out, and thanks for being direct.
>
>Moving  the qTox repo to an organization is absolutely possible, however as far  as I know, that >implies losing the issue tracker and breaking all links  to the current repo (?).
>Is there any concrete advantage you have in mind for moving the qTox repo to an organization?
>
>I'd  love to delegate some maintenance to people I trust, but the Tox  Foundation / Tox Project / Tox Organization doesn't exactly have the  best track record when it comes to resource handling and level-headed  decisions making.
>The current situation is not ideal, but  it helps shield qTox from the latest Tox drama, gross mismanagement of  resources, and people regularly going rogue.
>
>Now  I'm afraid that I haven't quite catched up with the community  discussions yet, but I'll be happy to work with you on resolving any  issue the community raises.

>Cheers.

**Comment by zetok** [comment]
@antis81 that's great news `:)`

>Moving the qTox repo to an organization is absolutely possible, however as far as I know, that >implies losing the issue tracker and breaking all links to the current repo (?).

About that part - issues are kept, and links are redirected to new repo, so that nothing is being lost. They are preserved, provided that repo is actually transferred, rather than forked.

**Comment by antis81** [comment]
@zetok I just accepted invitationto the qtox org. (currently readonly access of course) -- yay. :)
